<a href="https://colab.research.google.com/github/taoducminh/AIO-Exercise/blob/feature%2Fexercise-module2-week1/Numpy_Exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Bài tập 1: Numpy Cơ Bản

In [2]:
# Câu hỏi 1: Câu nào sau đây là đúng để tạo mảng 1 chiều từ 0 đến 9
import numpy as np
arr = np.arange(0, 10, 1)

In [6]:
# Câu hỏi 2: Cách tạo một mảng boolean 3x3 với tất cả giá trị là True
arr = np.ones((3, 3)) > 0
print(arr)
arr = np.ones((3, 3), dtype=bool)
print(arr)
arr = np.full((3, 3), fill_value=True, dtype=bool)
print(arr)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [5]:
# Câu hỏi 3: Kết quả của đoạn code sau đây:
import numpy as np
arr = np.arange(0, 10)
print(arr[arr % 2 == 1])

[1 3 5 7 9]


In [7]:
# Câu hỏi 4: Kết quả của đoạn code sau đây:
import numpy as np
arr = np.arange(0, 10)
arr[arr % 2 == 1] = -1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [8]:
# Câu hỏi 5: Kết quả của đoạn code sau đây:
import numpy as np
arr = np.arange(10)
arr_2d = arr.reshape(2, -1)
print(arr_2d)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [9]:
# Câu hỏi 6: Kết quả của đoạn code sau đây:
import numpy as np
arr1 = np.arange(10).reshape(2, -1)
arr2 = np.repeat(1, 10).reshape(2, -1)
c = np.concatenate([arr1, arr2], axis=0)
print("Result:\n", c)

Result:
 [[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [1]:
# Câu hỏi 7: Kết quả của đoạn code sau đây:
import numpy as np
arr1 = np.arange(10).reshape(2, -1)
arr2 = np.repeat(1, 10).reshape(2, -1)
c = np.concatenate([arr1, arr2], axis=1)
print("C = ", c)

C =  [[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


In [2]:
# Câu hỏi 8: Kết quả của đoạn code sau đây:
import numpy as np
arr = np.array([1, 2, 3])
print(np.repeat(arr, 3))
print(np.tile(arr, 3))

[1 1 1 2 2 2 3 3 3]
[1 2 3 1 2 3 1 2 3]


In [3]:
# Câu hỏi 9: Kết quả của đoạn code sau đây:
import numpy as np
a = np.array([2, 6, 1, 9, 10, 3, 27])
index = np.where((a >= 5) & (a <= 10))
print("result", a[index])


result [ 6  9 10]


In [4]:
# Câu hỏi 10: Kết quả của đoạn code sau đây:
import numpy as np

def maxx(x, y):
    if x >= y:
        return x
    else:
        return y

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

pair_max = np.vectorize(maxx, otypes=[float])
print(pair_max(a, b))

[6. 7. 9. 8. 9. 7. 5.]


In [5]:
# Câu hỏi 11: Kết quả của đoạn code sau đây:
import numpy as np

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

print("Result", np.where(a < b, b, a))


Result [6 7 9 8 9 7 5]


# Bài tập 2: Xử lý ảnh

In [8]:
# Câu hỏi 12: Hoàn thành đoạn code sau đây để chuyển ảnh màu sang ảnh xám dựa vào phương pháp Lightness:

# Download image
!gdown 1i9dqan21DjQoG5Q_VEvm0LrVwAlXD0vB

import matplotlib.image as mpimg
img = mpimg.imread('/content/dog.jpeg')

# Your Code Here
gray_img_01 = (np.max(img, axis=2) + np.min(img, axis=2)) / 2

gray_img_01[0, 0]

Downloading...
From: https://drive.google.com/uc?id=1i9dqan21DjQoG5Q_VEvm0LrVwAlXD0vB
To: /content/dog.jpeg
100% 33.7k/33.7k [00:00<00:00, 57.0MB/s]


102.5

In [9]:
# Câu hỏi 13: Hoàn thành đoạn code sau đây để chuyển ảnh màu sang ảnh xám dựa vào phương pháp Average:
# Your Code Here
gray_img_02 = np.mean(img, axis=2)

gray_img_02[0, 0]

107.66666666666667

In [10]:
# Câu hỏi 14: Hoàn thành đoạn code sau đây để chuyển ảnh màu sang ảnh xám dựa vào phương pháp Luminosity:
# Your Code Here
gray_img_03 = 0.21 * img[:,:,0] + 0.72 * img[:,:,1] + 0.07 * img[:,:,2]

gray_img_03[0, 0]

126.22999999999999

# Bài tập 3: Phân tích dữ liệu dạng bảng

In [14]:
# Download data
! gdown 1iA0WmVfW88HyJvTBSQDI5vesf-pgKabq
import pandas as pd
df = pd.read_csv('/content/advertising.csv')
data = df.to_numpy()

Downloading...
From: https://drive.google.com/uc?id=1iA0WmVfW88HyJvTBSQDI5vesf-pgKabq
To: /content/advertising.csv
100% 4.06k/4.06k [00:00<00:00, 19.4MB/s]


In [15]:
# Câu hỏi 15: Lấy giá trị lớn nhất và chỉ mục tương ứng của nó trên cột Sales:
max_sales = df['Sales'].max()
max_sales_index = df['Sales'].idxmax()

print(f"Max: {max_sales} - Index: {max_sales_index}")

Max: 27.0 - Index: 175


In [16]:
# Câu hỏi 16: Giá trị trung bình của cột TV là:
mean_tv = df['TV'].mean()

print(f"Mean of TV column: {mean_tv}")

Mean of TV column: 147.0425


In [17]:
# Câu hỏi 17: Số lượng bản ghi có giá trị tại cột Sales lớn hơn hoặc bằng 20 là:
count_sales_ge_20 = df[df['Sales'] >= 20].shape[0]

print(f"Number of records with Sales >= 20: {count_sales_ge_20}")

Number of records with Sales >= 20: 40


In [18]:
# Câu hỏi 18: Tính giá trị trung bình của cột Radio thoả mãn điều kiện giá trị tương ứng trên cột Sales lớn hơn hoặc bằng 15:
mean_radio = df[df['Sales'] >= 15]['Radio'].mean()

print(f"Mean of Radio column where Sales >= 15: {mean_radio}")

Mean of Radio column where Sales >= 15: 26.22293577981651


In [19]:
# Câu hỏi 19: Tính tổng các hàng của cột Sales với điều kiện giá trị Newspaper lớn hơn giá trị trung bình của cột Newspaper:
# Calculate the mean of the Newspaper column
mean_newspaper = df['Newspaper'].mean()

# Calculate the sum of the Sales column where Newspaper > mean_newspaper
sum_sales = df[df['Newspaper'] > mean_newspaper]['Sales'].sum()

print(f"Sum of Sales where Newspaper > mean of Newspaper: {sum_sales}")

Sum of Sales where Newspaper > mean of Newspaper: 1405.1


In [21]:
# Câu hỏi 20: Tạo mảng scores chứa các giá trị Good, Average và Bad dựa trên giá trị trung bình của cột Sales:
# Calculate the mean of the Sales column
mean_sales = df['Sales'].mean()

# Create a new array scores based on the condition
scores = ['Good' if sale > mean_sales else 'Bad' if sale < mean_sales else 'Average' for sale in df['Sales']]

# Print the result for scores[7:10]
print(scores)

['Good', 'Bad', 'Bad', 'Good', 'Good', 'Bad', 'Bad', 'Bad', 'Bad', 'Good', 'Bad', 'Good', 'Bad', 'Bad', 'Good', 'Good', 'Bad', 'Good', 'Bad', 'Bad', 'Good', 'Good', 'Bad', 'Good', 'Bad', 'Good', 'Bad', 'Good', 'Good', 'Bad', 'Good', 'Bad', 'Bad', 'Good', 'Bad', 'Good', 'Good', 'Bad', 'Bad', 'Good', 'Good', 'Good', 'Good', 'Good', 'Bad', 'Good', 'Bad', 'Good', 'Good', 'Bad', 'Good', 'Bad', 'Good', 'Good', 'Good', 'Good', 'Bad', 'Bad', 'Good', 'Good', 'Bad', 'Good', 'Good', 'Bad', 'Good', 'Bad', 'Bad', 'Bad', 'Good', 'Good', 'Good', 'Bad', 'Bad', 'Bad', 'Good', 'Bad', 'Bad', 'Bad', 'Bad', 'Bad', 'Bad', 'Good', 'Bad', 'Bad', 'Good', 'Good', 'Bad', 'Good', 'Bad', 'Good', 'Bad', 'Bad', 'Good', 'Good', 'Bad', 'Good', 'Good', 'Good', 'Good', 'Good', 'Good', 'Good', 'Good', 'Good', 'Good', 'Bad', 'Bad', 'Bad', 'Bad', 'Good', 'Good', 'Good', 'Good', 'Good', 'Bad', 'Bad', 'Bad', 'Bad', 'Good', 'Bad', 'Good', 'Bad', 'Good', 'Good', 'Good', 'Bad', 'Bad', 'Bad', 'Good', 'Bad', 'Bad', 'Good', 'Bad',

In [22]:
# Câu hỏi 21: Gọi giá trị trên cột Sales gần nhất với giá trị trung bình của cột Sales là A, tạo mảng scores:
# Calculate the mean of the Sales column
mean_sales = df['Sales'].mean()

# Find the value in the Sales column closest to the mean
closest_to_mean_sales = df['Sales'].iloc[(df['Sales'] - mean_sales).abs().argmin()]

# Create a new array scores based on the condition
scores = ['Good' if sale > closest_to_mean_sales else 'Bad' if sale < closest_to_mean_sales else 'Average' for sale in df['Sales']]

# Print the result for scores[7:10]
print(scores[7:10])

['Bad', 'Bad', 'Good']
